## Mini Exercise 1: One-Hot Coding

Imports

In [2]:
import pandas as pd
from sklearn.preprocessing import OneHotEncoder

1. Load “bike_types_times.csv” into your Python program.
2. The features are the Price of a bike, its 100m sprint time and its type – Aero, Climber or Endurance.

In [32]:
bike_types_times = pd.read_csv('bike_types_times.csv')
bike_types_times.head()

      Price  Time_100m_s Road_Bike_Type
0   9874.55         8.62           Aero
1   6230.91        11.95      Endurance
2  10222.88        10.01        Climber
3  10765.24        10.15        Climber
4   6789.45         8.93           Aero

3. One-Hot Encode the last feature, Road_Bike_Type, and print out the updated DataFrame with the encoded array.

In [33]:
# 1. Create encoder
encoder = OneHotEncoder(sparse_output = False)

# 2. Apply OHE
encoded = encoder.fit_transform(bike_types_times[["Road_Bike_Type"]])
print(f"Encoded NumPy Array:\n{encoded[:5]}")

# Create dataframe with custom col names
encoded_df = pd.DataFrame(
    encoded,
    columns = ['Road_Bike_Type_Aero', 'Road_Bike_Type_Climber', 'Road_Bike_Type_Endurance']
)
encoded_df.head()

# Drop RBT column from orig df
bike_types_times = bike_types_times.drop(columns = ['Road_Bike_Type'])

# Update orig df with new columns
bike_types_times = pd.concat(
    [bike_types_times, encoded_df],
    axis = 1
)

print("\nUpdated DataFrame:")
bike_types_times.head()

Encoded NumPy Array:
[[1. 0. 0.]
 [0. 0. 1.]
 [0. 1. 0.]
 [0. 1. 0.]
 [1. 0. 0.]]

Updated DataFrame:

,Price,Time_100m_s,Road_Bike_Type_Aero,Road_Bike_Type_Climber,Road_Bike_Type_Endurance
0,9874.55,8.62,1.0,0.0,0.0
1,6230.91,11.95,0.0,0.0,1.0
2,10222.88,10.01,0.0,1.0,0.0
3,10765.24,10.15,0.0,1.0,0.0
4,6789.45,8.93,1.0,0.0,0.0